### ISSUE TITLE
Setup Project Environment, Testing, and CI/CD Pipelines

### ISSUE THREAD

**Issue by dciborow** [dciborow/GitOpsDevHub#1]
**Objective**: Set up your project environment in Copilot workspace with the essential configurations for the application (React frontend + SignalR backend + CosmosDB), and integrate **GitHub Actions** pipelines to automate testing, deployment, and release processes.

#### Steps:

1. **Project Initialization**:
   - Ensure the basic project structure is ready with a **React frontend** and **ASP.NET Core backend**.
   - Set up **SignalR** in the backend and verify it works with the React frontend.
   - Add CosmosDB connection in the backend for data storage and retrieval.

2. **Install Dependencies**:
   - React frontend: Ensure you have `react`, `@microsoft/signalr`, `axios`, and any UI frameworks needed.
   - Backend: Ensure you have ASP.NET Core with `Microsoft.Azure.Cosmos` and `SignalR` packages.

3. **Local Testing**:
   - Create basic unit tests for both frontend and backend.
   - Mock external dependencies (CosmosDB, SignalR) for unit tests to ensure they run without network access.
   - Add initial integration tests that connect to live services (or mock services with fakes).

4. **GitHub Actions - CI Pipeline**:
   - Create a GitHub Actions workflow for **Continuous Integration (CI)**. This workflow should:
     - Install project dependencies.
     - Run unit tests (offline with mocks).
     - Run integration tests (with access to external services or fakes).

   **Example `ci.yml`**:
   ```yaml
   name: CI

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest
       
       steps:
       - uses: actions/checkout@v2

       - name: Set up Node.js for frontend
         uses: actions/setup-node@v2
         with:
           node-version: '14'

       - name: Install frontend dependencies
         run: npm install
         working-directory: ./frontend

       - name: Run frontend tests
         run: npm test
         working-directory: ./frontend

       - name: Set up .NET Core for backend
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: '5.0.x'

       - name: Install backend dependencies
         run: dotnet restore ./backend

       - name: Run backend unit tests
         run: dotnet test ./backend/tests
   ```

5. **GitHub Actions - CD Pipeline**:
   - Create a GitHub Actions workflow for **Continuous Deployment (CD)**. This workflow should:
     - Build the frontend and backend.
     - Deploy the application to your chosen environment (e.g., Azure Kubernetes Service (AKS), Azure App Service).

   **Example `cd.yml`**:
   ```yaml
   name: CD

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2

       # Build and Deploy Frontend
       - name: Build frontend
         run: npm run build
         working-directory: ./frontend

       - name: Deploy frontend
         run: |
           # Deploy to hosting service (e.g., Azure Static Web Apps)
           # Add deployment commands here

       # Build and Deploy Backend
       - name: Build backend
         run: dotnet publish ./backend -c Release -o ./publish

       - name: Deploy backend
         run: |
           # Deploy to hosting service (e.g., Azure App Service or AKS)
           # Add deployment commands here
   ```

6. **GitHub Actions - Release Pipeline**:
   - Create a **release pipeline** to automatically tag a new version when a release is created or a pull request is merged into `main`.
   - This pipeline should handle the versioning and release process, ensuring the application is in a releasable state.

   **Example `release.yml`**:
   ```yaml
   name: Release

   on:
     release:
       types: [created]

   jobs:
     release:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2

       - name: Install dependencies
         run: npm install
         working-directory: ./frontend

       - name: Build and tag release
         run: |
           npm run build
           git tag -a v${{ github.event.release.tag_name }} -m "Release ${{ github.event.release.tag_name }}"
           git push origin v${{ github.event.release.tag_name }}
   ```

7. **Verification**:
   - Run all pipelines and verify that:
     - The **CI pipeline** runs tests successfully.
     - The **CD pipeline** builds and deploys the application.
     - The **Release pipeline** tags the release and creates a version in the repository.

This task will get the project environment ready and ensure that you have **CI/CD** pipelines configured for testing, deployment, and releases. Each feature can be tracked through functional tests and GitHub Actions will provide automation for ensuring quality and stability.
